### ISSUE TITLE
Survey start and end notifications are not coming.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#218]
I checked the schedule and notification in Development environment. Both are working fine. But the survey Start and End notifications are not working.

**Comment by vivek-onepoint** [comment]
I have tested the service which used to send Survey Start and End Notification it working fine. The problem is with the user country setup (ex : you are expecting the start and end notification email according to Indian time and country set for user is Algeria, due to which some time email are not getting delivered on time). Please just check the country while setting up an new account or the existing account.

**Comment by onepointpb** [comment]
Receiving start and end notification after changing the country.
