### ISSUE TITLE
The Questionnaires list only shows the date and not the time making it hard to see rapid changes

### ISSUE THREAD

**Issue by dougmorris** [OnePointGlobal/OnePoint-Global-Account-Toolkit#221]
It is not possible to see which is the latest version. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/4094389/27951316-663ee03c-62fc-11e7-8c49-eabfa036bc5e.png)

**Comment by veereshms** [comment]
Time is getting displayed now, but there are other issues as mentioned below.
1) If edit questionnaire the time becomes 00:00:00
2) Time is getting displayed in UTC instead of local time
3) After refreshing the page some times if we try to expand the questionnaire then it shows "Loading....." message for indefinite time and won't load until we refresh the page  or expand questionnaire again.
![image](https://user-images.githubusercontent.com/26476914/28812377-1a4a5d54-76b2-11e7-917c-6fae9895e139.png)

4) In questionnaire list some times for any questionnaire if we directly click on edit button without expanding it then script file is not getting displayed under Script field and also we are not able to save the changes in this case.
![image](https://user-images.githubusercontent.com/26476914/28812370-0f1f4502-76b2-11e7-8da5-f4a09523c743.png)

5) For questionnaires created using question editor if we directly click on edit button without expanding it then progress dialog as shown below is getting displayed for indefinite time and only disappears if we refresh the page.
![image](https://user-images.githubusercontent.com/26476914/28812437-6760e1e4-76b2-11e7-8cbb-1b9c6a1e0a41.png)

**Comment by pavankumarkolla** [comment]
Need Discussion on Time is getting displayed in UTC instead of local time.

**Comment by pavankumarkolla** [comment]
Fixed in dev except second point(Time is getting displayed in UTC instead of local time).

**Comment by akshatha-opg** [comment]
Fixed in web API

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
