### ISSUE TITLE
Email notifications not working not receiving mails for any filter condition

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#283]
Email notifications not working not receiving mails for any filter condition, testing is done in development.

**Comment by veereshms** [comment]
It is working in staging may be this issue is because of notification service in dev server. Closing this issue for now and will reopen it again if this issue recurs.

**Comment by abhi-onepoint** [comment]
Just to make it clear (As you know filters cant be tested in staging), We keep updating the notification service with new enhancement in development server. So while working on it you may see notification filters not working. Let development team know when you test it in development environment, so that we can keep it unchanged for your time. or can give another time to test it. I believe you have had testing while I was working on sms notification filter, where I stopped the service.

**Comment by veereshms** [comment]
Ok will let you know when we need to test in dev. Thank you!
