### ISSUE TITLE
Clicking on the links to monitor results in the start/end Notification email is throwing "404 File or Directory Not Found" error in staging.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#308]
Clicking on the links to monitor results in the start/end Notification email is throwing "404 File or Directory Not Found" error in staging.

**Comment by vivek-onepoint** [comment]
Hi,
I have checked this issue in Dev Server and it works perfectly fine. While doing same in Staging the link is not working is because of the change in the link. Firstly the link was like (http://adminsuite.staging.onepointglobal.com) and i have seen that this link is been changed to (http://adminsuitestaging.onepointglobal.com). If for any reason we have updated the staging admin suite link we must update it everywhere we are using link to see reports or another purpose.

I have updated the link in staging server config file and it works perfectly fine after that.

**Comment by onepointpb** [comment]
Now the error message shows "Error. An error occurred while processing your request."

**Comment by vivek-onepoint** [comment]
I have changed some configuration to the service config files for default emailserver and changed the required URL's and restarted the service in staging. Tested it and it looks fine. As its working fine in Dev already.

Can you have a look again to it in staging server.

**Comment by onepointpb** [comment]
Now the start and end notifications are not coming at all in staging as well as in live.

**Comment by vivek-onepoint** [comment]
![start notification live](https://user-images.githubusercontent.com/28775558/30682358-0d99a50a-9ec7-11e7-987c-10e50e15adbb.png)

Start Email Notification Live Toolkit.

![end notification live](https://user-images.githubusercontent.com/28775558/30682414-3aba2a3c-9ec7-11e7-9612-67991ffbe2f3.png)

End Email Notification Live Toolkit.

I have Just scheduled an survey Invitation in live toolkit and its working perfectly fine for me. I got Invitation Email as well as the Start and End Email Notification With respect to the Survey. As you can see i have attached the screen shot of it.

Problem may be because of the country set or time zone. Please make sure its set correctly.

**Comment by onepointpb** [comment]
![profile_setting](https://user-images.githubusercontent.com/26476815/30683138-d200552c-9ec9-11e7-892d-89ef223a8b69.png)
My country and Time zone is set to India. 

I and Veeresh both have created new surveys. Still we are not getting the notification. It will be good to debug with you.

**Comment by onepointpb** [comment]
Today we tested again. For the first survey we received only the end notification.
After restarting the service we are now receiving the start and end notifications both.
