### ISSUE TITLE
Participant lists not available in Toolkit

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#336]
Hi,

I have few samples which were created in framework and toolkit while back, but currently there is no listing available in Toolkit and it doesn't allow me to create a new sample as well("+" symbol is greyed out. Because of this reason,we are not able to use this account for testing.

![participant](https://user-images.githubusercontent.com/28919270/30732233-2ef74a68-9f8f-11e7-9b11-b656233c31bc.png)

Account name: pavithra.r

**Comment by onepointraj** [comment]
In DB, themeType column was having Null value for few accounts. Updated the value to 1 (i.e app theme). Now it is working.

**Comment by pavithra-opg** [comment]
Hi Raj,
It works in my account now but the same issue is occurring for Tim's account as well(reported earlier).
Could you look into this and make sure it isn't happening in any other accounts.

**Comment by onepointraj** [comment]
Hi @pavithra-opg ,
from dot net team , vivek will look in to it.

**Comment by vivek-onepoint** [comment]
Hi,
There was an issue with respect to the themetype where value is set as null, as we attach the theme to anypanel or already attached to any panel it is coming as null because of which it was showing problem in displaying participants page is unable to show the panels.

The changes are related to Database which have been made and checked through postman, works perfectly fine in all the servers.

@pavithra-opg : Can u please confirm this changes once in live with tim's account.

**Comment by pavithra-opg** [comment]
Hi Vivek,
Thanks, panel details are displayed now for Tim's account. I have asked him to confirm if it looks fine at his end as well.

As per your confirmation, you have checked the details for all the accounts and this issue will not occur in other accounts.

Once I get a confirmation from Tim, will close the bug.

**Comment by pavithra-opg** [comment]
Tim,confirmed that the panels are visible in Account toolkit
