### ISSUE TITLE
Reset Password link isn't working when opened from Outlook

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#403]
Hi,
When we try to reset the password using Forgot Password, entered the email ID and receive an email with the Reset Password Link. 
Accessing this through gmail,redirects to the set password page but in case of Outlook, it takes me back to the Login page.

**Comment by vivek-onepoint** [comment]
Hi,

Outlook is not be able to handover the full url or hyperlink to browser when we click on the ResetPassword Link from it. Its an outlook issue not from our system.

It breaks the url after some special character like (#, @, &, and so on) because of which the page is redirected to Login page.

I have tried some solution for that, but it does not seems to work.

**Comment by pavithra-opg** [comment]
Works now
