### ISSUE TITLE
Notification Details is not Removing after deleting

### ISSUE THREAD

**Issue by nikul-opg** [OnePointGlobal/OnePoint-Global-Account-Toolkit#440]
In live If notification is deleted after that it's not removing from the list, I have to refresh the page for remove notification details from the list.
![screenshot 119](https://user-images.githubusercontent.com/44224714/52107350-f81af700-261b-11e9-8863-caf152daf75d.png)
![screenshot 120](https://user-images.githubusercontent.com/44224714/52107351-f8b38d80-261b-11e9-8351-19ca73ca8b2b.png)

**Comment by brijeshonepoint** [comment]
Hi @nikul-opg ,
I have checked this issue from my side. Delete notification API is not giving success status 200, instead directly it is giving response as [false], which had been sent earlier as status code 200 and list of remaining notifications.
Because of that list is not updating and update once page is refreshed.

Assigning this issue to @vivek-onepoint

**Comment by dougmorris** [comment]
@brijeshonepoint please can you share the exact server side response.

Thanks.

**Comment by brijeshonepoint** [comment]
![image](https://user-images.githubusercontent.com/38459171/58458008-aad01180-8145-11e9-9686-5beb7807c6eb.png)

![image](https://user-images.githubusercontent.com/38459171/58458339-9d675700-8146-11e9-90ca-6e9da2121544.png)


In the above image response is returning an array [false], which was earlier returning list of remaining notification or if last notification is deleted it was returning empty array [].

**Comment by dougmorris** [comment]
@brijeshonepoint please can you confirm the exact format of the list you are expecting. I presume it is Json and therefore looks a particular way?

**Comment by brijeshonepoint** [comment]
@dougmorris I am expecting below list which should be same as the response of /UserNotification/GetNotifications?surveyID otherwise I have to call /GetNotifications again to update the list after deleting. As per the code written in UI side, below updated list was coming earlier in the response of Delete Notification.

[{"FinishTime":null,"StartTime":"2019-04-16T09:40:00","NotificationID":142027,"Name":"test","Description":"desc","Medium":1,"JsonContent":"{\"Templateid\":424,\"Subject\":\"asdasd\",\"Type\":1,\"Content\":\"<p>asdasdasd</p>\",\"EmailServer\":38}","Type":2,"SubType":0,"SubTypeSpecified":true,"RefID":152999,"UserID":2182,"IsDeleted":false,"CreatedDate":"2018-10-12T09:39:50.1","LastUpdated":"2018-10-12T09:56:42.25"}]

**Comment by dougmorris** [comment]
@brijeshonepoint this is really useful. Many thanks! An update is being made available on dev for you to test against by @vivek-onepoint

**Comment by brijeshonepoint** [comment]
@vivek-onepoint Tested in dev, getting Survey Id's in response of delete API. Attached image.

![image](https://user-images.githubusercontent.com/38459171/58543848-d8888980-821d-11e9-8dba-b472735dfaea.png)

**Comment by vivek-onepoint** [comment]
@brijeshonepoint : Code is been updated in Development server. Please have a look once and let me now if it is still now working.

**Comment by brijeshonepoint** [comment]
Thanks @vivek-onepoint working fine now. Updated in dev, @nikul-opg please test once in dev. We will release to Staging and Live once you confirm.

**Comment by nikul-opg** [comment]
I checked the issue now in dev its working. issue is resolve.
