### ISSUE TITLE
"Enhancement" In most cases the message says "Are u sure...." instead of "Are you sure....." refer comments for few places where i have identified this and change this in all places and not limited to list given in comments

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Account-Toolkit#55]
1) Detaching questionnaire from survey
2) Detaching panel from survey
3) Delete theme
4) Delete panel
5) Delete panellist
6) Delete profile element

**Comment by onepointpb** [comment]
Please check all the texts that is used for validation alerts, success messages etc. 
1. There should be consistency. 
2. In a statement there should not be upper case letter.  
3. Even if it is coming from the api make necessary corrections.

**Comment by onepointpb** [comment]
1. The alert message to delete something should be consistent evrywhere i.e. "Are you sure, you want to delete?"
2. The error message on clicking Upload without selecting a file should be consistent i.e. "Please select a file."
3. Questionnaire, Sample and Location tab In Survey editor should have remove icon (X) rather than delete. The alert message to remove something should be consistent i.e. "Are you sure, you want to remove?"

**Comment by onepointpb** [comment]
1. Consistency is not maintained for the text "Are you sure, you want to delete?". Please check wherever it appears. 
2. The error message on clicking Upload without selecting a file should be consistent i.e. "Please select a file."

**Comment by onepointraj** [comment]
Fixed

**Comment by veereshms** [comment]
Verified.
