### ISSUE TITLE
Sample Management and Communication Inter dependent -If there are not email templates added in the communication module , the dropdown in the form remains empty and user cannot go further.

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-Account-Toolkit#83]
Need discussion with ui and qc on the implementation.

**Comment by onepointpb** [comment]
There should not be any validation for the "Choose Template" drop-down because instead of selecting anything from the drop-down the user can write their own content to be sent. (You can refer the existing Framework)

Instead you can provide validation for the Subject field and email content section to restrict the user from sending blank emails.

**Comment by kishanOPG** [comment]
Fixed

**Comment by veereshms** [comment]
In sample management If we don't choose email template from drop down menu then "Send" link is not working i.e. not able to send mail.

**Comment by kishanOPG** [comment]
Fixed in dev

**Comment by kishanOPG** [comment]
Fixed

**Comment by onepointpb** [comment]
Verified the fix.
